networks:
  web:    # sieć publiczna dla Traefika
    name: web  # Nazwa bez prefiksu projektu
    driver: bridge
  internal: # sieć prywatna między app a db
    driver: bridge
    internal: true
  db_management: # sieć dla dostępu z hosta (SSH tunnel)
    driver: bridge

services:
  traefik:
    image: traefik:v3.6.2
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.network=web"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Redirect HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      # Let's Encrypt
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=michalchawar+acme@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

  app:
    image: sok-web:latest
    build:
      context: .
      dockerfile: SOK.Web/Dockerfile
    container_name: sok-web
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      Admin__SqlServer: "Server=db,1433;Database=master;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True"
      ConnectionStrings__CentralDb: "Server=db,1433;Database=CentralDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True"
      Crypto__Key: "${CRYPTO_KEY}"
      Admin__Username: "${ADMIN_USERNAME}"
      Admin__Password: "${ADMIN_PASSWORD}"
      Admin__Email: "${ADMIN_EMAIL}"
      Admin__DisplayName: "${ADMIN_DISPLAY_NAME}"
      Admin__SeedExampleData: "${ADMIN_SEED_EXAMPLE_DATA:-false}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sok.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.sok.entrypoints=websecure"
      - "traefik.http.routers.sok.tls.certresolver=letsencrypt"
      - "traefik.http.services.sok-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.sok.service=sok-service"
    networks:
      - web
      - internal
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-CU20-ubuntu-22.04
    container_name: sok-db
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "127.0.0.1:1433:1433"  # Expose SQL Server port only on localhost
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - internal
      - db_management  # Dodatkowa sieć dla dostępu z hosta

volumes:
  mssql_data:
