services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: web-dev
    build: !reset null
    volumes:
      - .:/src
      - /src/SOK.Web/bin
      - /src/SOK.Web/obj
      - /src/SOK.Application/bin
      - /src/SOK.Application/obj
      - /src/SOK.Domain/bin
      - /src/SOK.Domain/obj
      - /src/SOK.Infrastructure/bin
      - /src/SOK.Infrastructure/obj
    entrypoint: ["dotnet", "watch", "run", "--urls=http://0.0.0.0:8080", "--non-interactive", "--project", "/src/SOK.Web/SOK.Web.csproj"]
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      DOTNET_WATCH_RESTART_ON_RUDE_EDIT: "true"
